// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Uu8t8Jj62JheF1hI5_6sLeKHUvrnns8',
    appId: '1:7117492319:web:c82f326d992bfa4191cbea',
    messagingSenderId: '7117492319',
    projectId: 'quit-smoking-app-bfb60',
    authDomain: 'quit-smoking-app-bfb60.firebaseapp.com',
    databaseURL: 'https://quit-smoking-app-bfb60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quit-smoking-app-bfb60.appspot.com',
    measurementId: 'G-K02KR1RV8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7g5pfl_YmGvbMkXvkwxFNUfoVvS_02I',
    appId: '1:7117492319:android:1198eab4a936f26691cbea',
    messagingSenderId: '7117492319',
    projectId: 'quit-smoking-app-bfb60',
    databaseURL: 'https://quit-smoking-app-bfb60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quit-smoking-app-bfb60.appspot.com',
  );
}
